--value date cannot be before trade date
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(1,'SPOT','SELECT 1 FROM TRADES WHERE ID = :id AND VALUE_DATE > TRADE_DATE','HERE VALUE DATE SHOULD BE AFTER TRADE DATE');
--if the counterparty is one of the supported ones
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(2,'ALL','SELECT 1 FROM TRADES WHERE ID = :id AND CUSTOMER IN (''PLUTO1'',''PLUTO2'')','CURRENTLY ONLY ALLOWED CUSTOMER IS PLUTO1 AND PLUTO2');
--validate currencies if they are valid ISO codes (ISO 4217)
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(3,'ALL','SELECT 1 FROM TRADES TD,ISO4217 ISO WHERE TD.ID = :id AND COALESCE(TD.PAY_CCY,''USD'') = ISO.alphabetic_Code' ,'PLEASE CHOOSE VALID ISO CODE FOR PAY CURRENCY' );
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(4,'ALL','SELECT 1 FROM TRADES TD,ISO4217 ISO WHERE TD.ID = :id AND COALESCE(TD.PREMIUM_CCY,''USD'') = ISO.alphabetic_Code','PLEASE ENTER CORRECT PREMIUM CURRENCY VALUE' );
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(5,'ALL','SELECT 1 FROM TRADES TD,ISO4217 ISO WHERE TD.ID = :id AND COALESCE(TD.PREMIUM_TYPE,''USD'') = ISO.alphabetic_Code', 'PLEASE CHOOSE VALID ISO CODE FOR PREMIUM TYPE');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(6,'ALL','SELECT 1 FROM TRADES TD,ISO4217 ISO WHERE TD.ID = :id AND SUBSTRING(TD.CCY_PAIR,0, 3) = ISO.alphabetic_Code','PLEASE CHOOSE VALID ISO CODE FOR CURRENCY PAIR' );
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(7,'ALL','SELECT 1 FROM TRADES TD,ISO4217 ISO WHERE TD.ID = :id AND SUBSTRING(TD.CCY_PAIR,4) = ISO.alphabetic_Code','PLEASE CHOOSE VALID ISO CODE FOR CURRENCY PAIR' );


INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(8,'VANILLAOPTION','SELECT 1 FROM TRADES WHERE ID = :id AND STYLE IN (''AMERICAN'',''EUROPEAN'')','ALLOWED STYLE ONLY AMERICAN AND EUROPEAN');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(9,'VANILLAOPTION','SELECT 1 FROM TRADES WHERE ID = :id AND EXPIRY_DATE < DELIVERY_DATE','EXIRY DATE SHOULD BE BEFORE DELIVERY DATE');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(10,'VANILLAOPTION','SELECT 1 FROM TRADES WHERE ID = :id AND PREMIUM_DATE < DELIVERY_DATE','PREMIUM DATE SHOULD BE BEFORE DELIVERY DATE');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(11,'VANILLAOPTION','SELECT 1 FROM TRADES WHERE ID = :id AND STYLE = ''AMERICAN'' AND EXCERCISE_START_DATE IS NOT NULL ','EXCERCISE START DATE CAN NOT BE NULL AS STYLE IS AMERICAN HERE');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(12,'VANILLAOPTION','SELECT 1 FROM TRADES WHERE ID = :id AND STYLE = ''AMERICAN'' AND COALESCE(EXCERCISE_START_DATE,''1970-01-01'') > TRADE_DATE ','EXCERCISE START DATE SHOULD BE AFTER TRADE DATE AS STYLE IS AMERICAN HERE');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(13,'VANILLAOPTION','SELECT 1 FROM TRADES WHERE ID = :id AND STYLE = ''AMERICAN'' AND COALESCE(EXCERCISE_START_DATE,''1970-01-01'') < EXPIRY_DATE ','EXCERCISE START DATE SHOULD BE BEFORE EXPIRY DATE AS STYLE IS AMERICAN HERE');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(14,'FORWARD','SELECT 1 FROM TRADES WHERE ID = :id AND VALUE_DATE > TRADE_DATE','HERE VALUE DATE SHOULD BE AFTER TRADE DATE');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(15,'SPOT','SELECT 1 FROM TRADES WHERE ID = :id AND VALUE_DATE IS NOT NULL ','VALUE DATE SHOULD BE AVAILABLE FOR SPOT FX TRANSACTION');
INSERT INTO BIZ_RULE(ID,TYPE,CUSTOM_QUERY,EXCEPTION_MESSAGE) VALUES(16,'FORWARD','SELECT 1 FROM TRADES WHERE ID = :id AND VALUE_DATE IS NOT NULL ','VALUE DATE SHOULD BE AVAILABLE FOR FORWARD FX TRANSACTION');


INSERT INTO ISO4217(alphabetic_Code,COUNTRY) VALUES('USD','USA');
INSERT INTO ISO4217(alphabetic_Code,COUNTRY) VALUES('EUR','EUROPE');